Feat/deck crud and user crud
gbrad777/TcgPocket pull request #21
Opened 2023-09-06 04:09 UTC by DeannaShort

Deck and user crud

2023-09-07 01:26 UTC, xalluna commented on TcgPocket/Features/Decks/Queries/GetAllDecksQuery.cs
> +            .ToListAsync(cancellationToken: cancellationToken);
Unnecessary explicit parameter
```suggestion
            .ToListAsync(cancellationToken);
```

2023-09-07 01:35 UTC, xalluna commented on TcgPocket/Features/Users/Queries/GetUserByIdQuery.cs
> +        var user = _userManager.Users.SingleOrDefault(x => x.Id ==query.Id);
***NIT***: give the `query.Id some space`
```suggestion
        var user = _userManager.Users.SingleOrDefault(x => x.Id == query.Id);
```

2023-09-07 01:39 UTC, xalluna commented on TcgPocket/Startup.cs
>      }
I know this is my bad, but can you remove the comments from this 😅

2023-09-07 01:58 UTC, xalluna submitted a review, later dismissed

2023-09-07 02:00 UTC, xalluna submitted a review, later dismissed

2023-09-07 04:09 UTC, xalluna approved these changes

2023-09-07 17:54 UTC, gbrad777 requested changes

2023-09-07 17:54 UTC, gbrad777 commented on TcgPocket/Features/Roles/RoleConfiguration.cs
> +        builder.ToTable("Roles", "identity");
does this need to be under an identity schema? if not please make the "identity" part "dbo"

2023-09-07 17:54 UTC, gbrad777 commented on TcgPocket/Features/UserRoles/UserRoleConfiguration.cs
> +        builder.ToTable("UserRoles", "identity");
same question as before

2023-09-07 17:54 UTC, gbrad777 commented on TcgPocket/Features/Users/Commands/UpdatePasswordCommand.cs
> +    [JsonIgnore]
whats this doing?

2023-09-07 17:54 UTC, gbrad777 commented on TcgPocket/Features/Users/Commands/UpdatePasswordCommand.cs
> +            return Error.AsResponse("Current password is incorrect.", "current password");
if this error is returned to the front end, we probably shouldnt be telling them that this particular password isnt correct, it would probably be better to return a more generic error.

2023-09-07 17:54 UTC, gbrad777 commented on TcgPocket/Features/Users/Commands/UpdatePasswordCommand.cs
> +public class UpdatePasswordCommand : IRequest<Response>
instead of checking by id since the user would be changing the password without necessarily accessing their account, wouldnt it be better to take in a user name instead of an id and then validate the user from that before changing the password?

2023-09-07 17:54 UTC, gbrad777 commented on TcgPocket/Features/Users/Commands/UpdateUserCommand.cs
> +public class UpdateUserCommand : IRequest<Response<UserGetDto>>
im guessing this would be like when a user is signed in?

2023-09-07 17:54 UTC, gbrad777 commented on TcgPocket/Features/Users/User.cs
> +public class UserCreateUpdateDto: UserDto
why this exist?

2023-09-07 17:54 UTC, gbrad777 commented on TcgPocket/Features/Users/User.cs
> +    public string UserName { get; set; }
should just be "Username"

2023-09-07 17:54 UTC, gbrad777 commented on TcgPocket/Features/Users/UserConfiguration.cs
> +        builder.ToTable("Users", "identity");
same question as before

2023-09-07 20:04 UTC, xalluna commented on TcgPocket/Startup.cs
> +                "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789-._@+";
why

2023-09-07 20:05 UTC, xalluna commented on TcgPocket/Features/Users/User.cs
> +    public string UserName { get; set; }
That field on IdenityUser is `UserName`

2023-09-07 20:06 UTC, xalluna commented on TcgPocket/Features/Users/User.cs
> +public class UserCreateUpdateDto: UserDto
cant put a password on a base dto. Honestly probably not required for updating tho

2023-09-07 20:07 UTC, xalluna commented on TcgPocket/Features/Users/Commands/UpdateUserCommand.cs
> +public class UpdateUserCommand : IRequest<Response<UserGetDto>>
this is for updating user info

2023-09-07 20:07 UTC, xalluna commented on TcgPocket/Features/Users/Commands/UpdatePasswordCommand.cs
> +public class UpdatePasswordCommand : IRequest<Response>
that's fair, I agree

2023-09-07 20:07 UTC, xalluna commented on TcgPocket/Features/Users/Commands/UpdatePasswordCommand.cs
> +            return Error.AsResponse("Current password is incorrect.", "current password");
Good catch

2023-09-07 20:09 UTC, xalluna commented on TcgPocket/Features/Roles/RoleConfiguration.cs
> +        builder.ToTable("Roles", "identity");
Respectfully, no. It does not *have* to be in `identity` but it should be. Auth stuff is separate from business logic and should be in a different schema

2023-09-09 00:05 UTC, DeannaShort commented on TcgPocket/Features/Roles/RoleConfiguration.cs
> +        builder.ToTable("Roles", "identity");
I agree with Brandon on this.

2023-09-09 00:06 UTC, DeannaShort commented on TcgPocket/Features/Users/Commands/UpdatePasswordCommand.cs
> +    [JsonIgnore]
Ignores the field below so that we arent requesting Id [FromRoute] and Id [FromBody]

2023-09-09 00:06 UTC, DeannaShort commented on TcgPocket/Features/Users/Commands/UpdateUserCommand.cs
> +public class UpdateUserCommand : IRequest<Response<UserGetDto>>
Yeah

2023-09-09 00:07 UTC, DeannaShort commented on TcgPocket/Features/Users/User.cs
> +public class UserCreateUpdateDto: UserDto
Name changed :)

2023-09-09 00:29 UTC, DeannaShort commented on TcgPocket/Startup.cs
> +                "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789-._@+";
I feel this is the most efficient way to access this string.

2023-09-09 02:13 UTC, xalluna commented on TcgPocket/Features/Roles/RolesController.cs
> +    }
You should be getting the Dto from the body, not the entire command.

```suggestion
    [HttpPost]
    public async Task<ActionResult<Response<RoleGetDto>>> CreateRole([FromBody] RoleDto data)
    {
        var response = await _mediator.Send(new CreateRoleCommand { Role = data });

        return response.HasErrors
            ? BadRequest(response)
            : CreatedAtRoute(nameof(GetRoleById), new { response.Data.Id }, response);
    }
```

2023-09-09 02:16 UTC, xalluna commented on TcgPocket/Features/Users/UsersController.cs
> +    }
Should be getting just the `roleName` from the body, not the whole command

```suggestion
    [HttpPost("{id:int}/roles")]
    public async Task<ActionResult<Response<UserRoleDto>>> AddRoleToUser([FromRoute] int id, [FromBody] string roleName)
    {
        var response = await _mediator.Send(new AddRoleToUserCommand { Id = id, RoleName = roleName});

        return response.HasErrors
            ? BadRequest(response)
            : CreatedAtRoute(nameof(GetUserById), new { response.Data.Id }, response);
    }
```

2023-09-09 02:19 UTC, xalluna commented on TcgPocket/Features/Users/UsersController.cs
> +    }
If we are going to get the whole command from the body, we might as well just use it 😄 
Also, we don't use the `id` here so it can be removed from the route.

```suggestion
    [HttpPut("password-update", Name = nameof(UpdatePassword))]
    public async Task<ActionResult<Response<UserGetDto>>> UpdatePassword(
        [FromBody] UpdatePasswordCommand data)
    {
        var response = await _mediator.Send(data);

        return response.HasErrors ? BadRequest(response) : Ok(response);
    }
```

2023-09-09 02:20 UTC, xalluna commented on TcgPocket/Features/Users/UsersController.cs
> +    }
We should just get the `roleName` instead of the entire command.

```suggestion
    [HttpDelete("{id:int}/role")]
    public async Task<ActionResult<Response>> RemoveRoleFromUser([FromRoute] int id, [FromBody] string roleName)
    {
        var response = await _mediator.Send(new RemoveRoleFromUserCommand { UserId = id, RoleName = roleName });

        return response.HasErrors ? BadRequest(response) : Ok(response);
    }
```

2023-09-09 02:22 UTC, xalluna commented on TcgPocket/Features/Users/Commands/AddRoleToUserCommand.cs
> +    [JsonIgnore]
If we just get the `roleName` from the body, then we don't need to ignore this.
***also please don't forget to remove the import***

2023-09-09 02:22 UTC, xalluna commented on TcgPocket/Features/Users/Commands/RemoveRoleFromUserCommand.cs
> +    [JsonIgnore]
If we just get the `roleName` from the body, then we don't need to ignore this.
***also please don't forget to remove the import***

2023-09-09 02:24 UTC, xalluna commented on TcgPocket/Features/Users/Commands/UpdatePasswordCommand.cs
> +    [JsonIgnore]
this would now, then, ignore the `UserName` and isn't needed.

2023-09-09 02:25 UTC, xalluna commented on TcgPocket/Features/Users/Commands/UpdatePasswordCommand.cs
> +        var user = _userManager.Users.FirstOrDefault(x => x.UserName.Equals(command.UserName));
This avoids potential null reference exceptions and is functionally the same.

```suggestion
        var user = _userManager.Users.FirstOrDefault(x => x.UserName == command.UserName);
```

2023-09-09 02:27 UTC, xalluna commented on TcgPocket/Features/Users/Commands/UpdatePasswordCommand.cs
> +        }
This might be a more appropriate message for the user. This way bad actors are not certain of which piece of info is incorrect, therefore cannot determine if a username exists or something.

```suggestion
        if (user is null)
        {
            return Error.AsResponse("Username or password is incorrect.");
        }

        var correctPassword = await _userManager.CheckPasswordAsync(user, command.CurrentPassword);

        if (!correctPassword)
        {
            return Error.AsResponse("Username or password is incorrect.");
        }
```

2023-09-10 06:44 UTC, xalluna submitted a review, later dismissed

2023-09-10 23:49 UTC, gbrad777 commented on TcgPocket/Features/Roles/RolesController.cs
> +    public async Task<ActionResult<Response<List<Role>>>> GetAllRoles()
is it an identity thing to return the actual role entity?

2023-09-10 23:49 UTC, gbrad777 commented on TcgPocket/Features/Roles/RolesController.cs
> +    public async Task<ActionResult<Response<Role>>> GetRoleById([FromRoute] int id)
same thing here

2023-09-10 23:49 UTC, gbrad777 commented on TcgPocket/Features/Roles/RolesController.cs
> +    public async Task<ActionResult<Response<Role>>> UpdateRole([FromRoute] int id,
here as well

2023-09-10 23:49 UTC, gbrad777 commented on TcgPocket/Features/Users/Validators/UserDtoValidator.cs
> +using System.Text.RegularExpressions;
since we do a phone number regex here do we want an email one as well bc as of now incorrect emails can be input

2023-09-10 23:49 UTC, gbrad777 commented on TcgPocket/Features/Users/UsersController.cs
>          [FromBody] UpdatePasswordCommand data)
is there any reason we're passing a command in here instead of a dto?

2023-09-10 23:56 UTC, DeannaShort commented on TcgPocket/Features/Users/Validators/UserDtoValidator.cs
> +using System.Text.RegularExpressions;
The following code on the UserDto Validator validates email input: 
 ```
RuleFor(x => x.Email)
            .EmailAddress();
```

2023-09-10 23:59 UTC, DeannaShort commented on TcgPocket/Features/Users/UsersController.cs
>          [FromBody] UpdatePasswordCommand data)
It felt weird to have a Dto just for password update. Is there a reason that creating a Dto would be more beneficial instead of passing the command? If so, I can def change it.

2023-09-11 00:01 UTC, DeannaShort commented on TcgPocket/Features/Roles/RolesController.cs
> +    public async Task<ActionResult<Response<List<Role>>>> GetAllRoles()
Good point. This was something I missed when I changed our stuff to use a custom Role instead of Identity's. I'll change these all to return RoleGetDtos :)

2023-09-11 00:33 UTC, gbrad777 commented on TcgPocket/Features/Users/Validators/UserDtoValidator.cs
> +using System.Text.RegularExpressions;
when i was testing i did "email@.com" and it took it, if we dont care that much then its fine but just wanted to put it out there

2023-09-11 00:33 UTC, gbrad777 commented on TcgPocket/Features/Users/Validators/UserDtoValidator.cs
> +using System.Text.RegularExpressions;
while testing i did "email@.com" and it takes that as valid, if we dont care thats fine for now but it does still accept this invalid format

2023-09-11 00:35 UTC, gbrad777 commented on TcgPocket/Features/Users/UsersController.cs
>          [FromBody] UpdatePasswordCommand data)
feel free to tell me otherwise, but these commands and queries are specifically mediatr requests, so to me it doesnt make sense that the front end would send requests, but instead sends the data that makes up the request.

2023-09-11 03:13 UTC, xalluna commented on TcgPocket/Features/Users/Validators/UserDtoValidator.cs
> +using System.Text.RegularExpressions;
this is in production on all of E3's project and the reason is because email validation is fucking insane

its fine tbh

2023-09-11 03:25 UTC, DeannaShort commented on TcgPocket/Features/Users/UsersController.cs
>          [FromBody] UpdatePasswordCommand data)
That makes perfect beautiful sense. I updated the code to pass a Dto now.

2023-09-11 04:45 UTC, gbrad777 approved these changes

2023-09-11 04:53 UTC, merged