Feat/user and account
gbrad777/TcgPocket pull request #28
Opened 2023-09-19 03:45 UTC by zoe-klein

2023-09-19 03:47 UTC, DeannaShort commented
Is the intent to merge into main?

2023-09-19 17:04 UTC, DeannaShort commented on TcgPocket/App/src/components/buttons/DeleteButton.tsx
> +  color: theme.white,
```suggestion
  backgroundColor: theme.colors.red,
  '&:hover': {
    backgroundColor: 'darkred',
  },
  color: theme.white,
```

I would recommend something like this for the Delete button. At the moment, when you hover over it, it turns blue.

2023-09-19 17:07 UTC, DeannaShort commented on TcgPocket/App/src/pages/settings/SettingsPage.tsx
![image](https://github.com/gbrad777/TcgPocket/assets/113717324/a706d537-c2b9-47f3-88f2-b680efd66419)

Updating the password, triggers a success notification for SignedIn.

2023-09-19 17:09 UTC, DeannaShort commented on TcgPocket/App/src/pages/settings/SettingsPage.tsx
I love the tabbing for the settings because this is something we will add more to, however, on this actual page, Imo, there should be some type of generalized header so they know this is an account update page

2023-09-19 17:11 UTC, DeannaShort commented on TcgPocket/App/src/pages/settings/modules/PasswordForm.tsx
> +        value !== values.newPassword ? 'Passwords do not match' : null,
Is there any way we can check to make sure we arent making a useless call if someone tries to update their password with the same password they already have? This could be something we could handle on the backend but I think it would be nice to reduce API call. Would like to know your thoughts on this.

2023-09-19 19:05 UTC, zoe-klein commented on TcgPocket/App/src/pages/settings/SettingsPage.tsx
Yes, this is intentional as updating the password causes the user to be logged out. I can get rid of the success message but unless there is another way to keep them logged in, the code for logging in has to stay.

2023-09-19 19:06 UTC, zoe-klein commented on TcgPocket/App/src/pages/settings/modules/PasswordForm.tsx
> +        value !== values.newPassword ? 'Passwords do not match' : null,
see <conversation we had before you left>

2023-09-19 19:42 UTC, DeannaShort commented on TcgPocket/App/src/pages/settings/modules/PasswordForm.tsx
> +        value !== values.newPassword ? 'Passwords do not match' : null,
![image](https://github.com/gbrad777/TcgPocket/assets/113717324/912c6657-6c68-4a47-bf0d-26d2aca61be2)
```suggestion
      currentPassword: (value) => (value === '' ? 'Cannot be Empty' : null),
       newPassword: (value, values) =>
          value === values.currentPassword
          ? 'Must be different than current password.'
          : validatePassword(value)
          ? 'Invalid Password'
          : null,
```
This works to do what I was trying to describe.

2023-09-19 19:56 UTC, DeannaShort commented on TcgPocket/App/src/pages/settings/modules/PasswordForm.tsx
> +    form.values.newPasswordConfirmation === '';
```suggestion
  const determineDisabled = !form.isValid();
```

This should make sure the button is not enabled until everything in the form complies to the validation rules.

2023-09-19 21:06 UTC, zoe-klein commented on TcgPocket/App/src/pages/settings/modules/PasswordForm.tsx
> +    form.values.newPasswordConfirmation === '';
I remember Brandon saying something about this causing issues ? I'm not too sure so I'll leave the comment for now until we are sure :)

2023-09-19 21:10 UTC, xalluna commented on TcgPocket/App/src/pages/settings/modules/PasswordForm.tsx
> +    form.values.newPasswordConfirmation === '';
If there are no empty fields, you should let the user push the button. Then and only then if the form is still invalid, display the form errors from the frontend.

2023-09-19 21:15 UTC, zoe-klein commented on TcgPocket/App/src/pages/settings/modules/PasswordForm.tsx
> +    form.values.newPasswordConfirmation === '';
To make sure I'm understanding correctly, even if a user types in an email in the wrong format, they should still be able to click submit, at which time the errors appear?

2023-09-19 21:46 UTC, xalluna commented on TcgPocket/App/src/pages/settings/modules/PasswordForm.tsx
> +    form.values.newPasswordConfirmation === '';
If you cannot press the button and it's for some obscure reason then the user will be confused and frustrated. Ideally any given field should be validated onBlur, but on submit before actually talking to the api is sufficient.

2023-09-20 00:09 UTC, DeannaShort submitted a review, later dismissed
Really nice work Zoe! :)

2023-09-27 23:35 UTC, xalluna requested changes

2023-09-27 23:35 UTC, xalluna commented on TcgPocket/App/src/pages/settings/SettingsPage.tsx
> +];
```suggestion
type Tab = {
  label: string;
  icon: JSX.Element | undefined;
  element: JSX.Element | undefined;
};

const tabs: Tab[] = [
  { label: 'Account', icon: <IconUser />, element: <AccountTab /> },
];
```

2023-09-27 23:35 UTC, xalluna commented on TcgPocket/App/src/pages/settings/SettingsPage.tsx
> +];
We  strongly type things when possible.

2023-09-27 23:35 UTC, xalluna commented on TcgPocket/App/src/pages/settings/modules/AccountTab.tsx
> +            />
Since we are getting the user from the context, instead of passing the user as a prop we can just grab it from the context in the child components themselves.

2023-09-27 23:35 UTC, xalluna commented on TcgPocket/App/src/pages/settings/modules/AccountTab.tsx
> +  };
This probably shouldn't exist in the first place, but if it does need to exist, it should be defined ans used in the `PasswordForm` component.

2023-09-27 23:35 UTC, xalluna commented on TcgPocket/App/src/pages/settings/modules/DeleteAccount.tsx
> +          <Flex gap={8} justify={'flex-end'} sx={{ paddingTop: '8px' }}>
The `sx` should be defined a the bottom of the page 😔

2023-09-27 23:35 UTC, xalluna commented on TcgPocket/App/src/pages/settings/modules/PasswordForm.tsx
> +    <form onSubmit={form.onSubmit(handleSubmit)} onReset={handleReset}>
The handleReset function is not needed, just use `form.reset`

2023-09-27 23:35 UTC, xalluna commented on TcgPocket/App/src/pages/settings/modules/PersonalInformationForm.tsx
> +      <header> Personal Information </header>
```suggestion
type PersonalInformationFormProps = {
  user: UserGetDto;
};

type PersonalInformationFormDto = {
  id: number;
  userName: string | null;
  email: string | null;
  phoneNumber: string | null;
};

export function PersonalInformationForm({
  user,
}: PersonalInformationFormProps): React.ReactElement {
  const { validateTextInput, validateEmail, validatePhoneNumer } =
    useFormValidation();

  const initialValues: PersonalInformationFormDto = {
    id: user.id,
    userName: null,
    phoneNumber: null,
    email: null,
  };

  const form = useForm({
    initialValues: initialValues,
    validateInputOnBlur: true,
    validate: {
      userName: (value) =>
        validateTextInput(value ?? '') ? 'Invalid Username' : null,
      phoneNumber: (value) =>
        validatePhoneNumer(value ?? '') ? 'Invalid Phone Number' : null,
      email: (value) => (validateEmail(value ?? '') ? 'Invalid Email' : null),
    },
  });

  const handleSubmit = async (values: PersonalInformationFormDto) => {
    const userToUpdate: UserGetDto = {
      id: values.id,
      userName: values.userName ?? user.userName,
      email: values.email ?? user.email,
      phoneNumber: values.phoneNumber ?? user.phoneNumber,
    };

    const { payload } = await dispatch(updateUserInformation(userToUpdate));

    if (!payload) {
      return;
    } else if (payload.hasErrors) {
      payload.errors.forEach((err) => error(err.message));
      return;
    } else {
      success('User Information Updated');
    }
  };

  const determineDisabled =
    (form.values.userName === user.userName &&
      form.values.phoneNumber === user.phoneNumber &&
      form.values.email === user.email) ||
    !form.isValid();

  return (
    <form onSubmit={form.onSubmit(handleSubmit)} onReset={form.reset}>
      <header> Personal Information </header>
```

2023-09-28 01:50 UTC, zoe-klein commented on TcgPocket/App/src/pages/settings/modules/AccountTab.tsx
> +            />
Yes but passing as props allows us to pass in the user whenever it is defined and then we don't have to worry about handling the user being null or undefined in the forms. Unless there's a reason we shouldn't do this, I think this way is fine.

2023-09-28 01:58 UTC, zoe-klein commented on TcgPocket/App/src/pages/settings/modules/AccountTab.tsx
> +  };
yeye you're right. I never moved and I should have. But it shouldnt even be needed anymore soooooooooooooooo

2023-09-28 02:05 UTC, xalluna commented on TcgPocket/App/src/pages/settings/modules/PersonalInformationForm.tsx
> +      <header> Personal Information </header>
I got lost and the moment and forgot to explain. 

Basically, the form being prefilled with the user's data is a bit odd. I really like the way the data looks as a placeholder, but having it prefilled makes it hard to tell if you, as a user, made changes. Also, small changes that could have been made by accident may not get noticed.

Also I'm not a big fan of always sending up all of the user's info to be updated. I don't really have a good justification, but it feels yucky to me.

2023-09-28 02:17 UTC, zoe-klein commented on TcgPocket/App/src/pages/settings/modules/PersonalInformationForm.tsx
> +      <header> Personal Information </header>
I personally do like to see what information is there before I change it. If I forgot that I updated my phone number, I don't have to wonder whether or not I already did if I can see the value there. I'm okay with that information being displayed in the placeholder instead of already being filled out though 🙂

2023-09-28 02:24 UTC, xalluna commented on TcgPocket/App/src/pages/settings/modules/PasswordForm.tsx
> +        <SecondaryButton type="reset"> Cancel </SecondaryButton>
A cancel button shouldn't be clickable if it's not going to do anything, so it should be disabled until the user touches the form. i.e. the form needs to be `dirty` to be clickable

```suggestion
        <SecondaryButton type="reset" disabled={!form.dirty()} > Cancel </SecondaryButton>

2023-09-28 02:25 UTC, xalluna commented on TcgPocket/App/src/pages/settings/modules/PersonalInformationForm.tsx
> +        <SecondaryButton type="reset">Cancel</SecondaryButton>
```suggestion
        <SecondaryButton type="reset" disabled={!form.dirty()} > Cancel </SecondaryButton>

2023-09-29 14:57 UTC, DeannaShort approved these changes

2023-09-29 15:00 UTC, xalluna approved these changes

2023-09-29 22:55 UTC, merged