Feat/filtering
gbrad777/TcgPocket pull request #35
Opened 2023-10-02 05:31 UTC by xalluna

filter stuff and things

2023-10-02 06:21 UTC, DeannaShort requested changes
Really nice work, All I see are these small changes.

2023-10-02 06:21 UTC, DeannaShort commented on TcgPocket/Shared/PagedResult/QueryableExtensions.cs
> +                Expression.Equal(entityField, Expression.Constant(convertedFieldValue, entityFieldType));
```suggestion
            Expression filterExpression = null;

            if (field.PropertyType == typeof(string))
            {
                filterExpression =
                    Expression.Call(entityField, "Contains", null, Expression.Constant(convertedFieldValue));
            }
            else
            {
                filterExpression =
                    Expression.Equal(entityField, Expression.Constant(convertedFieldValue, entityFieldType));
            }
```
Would suggest adding something like this for fields that are string types so that we can filter by portions of string rather an exact matches.

2023-10-02 06:21 UTC, DeannaShort commented on TcgPocket/Features/Cards/CardsController.cs
> +        public async Task<ActionResult<Response<PagedResult<CardGetDto>>>>
```suggestion
        public async Task<ActionResult<Response<PagedResult<CardDetailDto>>>> 
```
Rec. changing here and inside of the GetPagedCardsQuery so that card attributes are included

2023-10-02 06:21 UTC, DeannaShort commented on TcgPocket/Features/Users/Queries/GetAllCardsByGameIdAndUserIdQuery.cs
Same thing here since you already touched this file, would you mind changing to return a CardDetailDto pls?

2023-10-02 15:02 UTC, xalluna commented on TcgPocket/Shared/PagedResult/QueryableExtensions.cs
> +                Expression.Equal(entityField, Expression.Constant(convertedFieldValue, entityFieldType));
beautiful 😊

2023-10-03 01:41 UTC, DeannaShort approved these changes

2023-10-03 22:13 UTC, zoe-klein submitted a review, later dismissed

2023-10-03 22:35 UTC, DeannaShort approved these changes

2023-10-04 01:16 UTC, zoe-klein approved these changes

2023-10-04 06:21 UTC, gbrad777 commented
i stand by what i said, you're a crazy man, and i love it

2023-10-04 06:21 UTC, gbrad777 approved these changes

2023-10-04 15:49 UTC, merged