register services
gbrad777/TcgPocket pull request #9
Opened 2023-08-26 00:14 UTC by xalluna

registered services and cleaned project of gitignored files

2023-08-26 01:54 UTC, gbrad777 requested changes

2023-08-26 01:54 UTC, gbrad777 commented on TcgPocket/Startup.cs
> +}
add program config stuff to here and then have program make builder using this startup file

2023-08-27 22:35 UTC, gbrad777 commented on TcgPocket/Startup.cs
> +        // builder;
does this need to be removed?

2023-08-27 22:35 UTC, gbrad777 commented on TcgPocket/Migrations/20230826051236_Initial.cs
> +﻿using Microsoft.EntityFrameworkCore.Migrations;
was this initial migration needed?

2023-08-27 22:43 UTC, xalluna commented on TcgPocket/Migrations/20230826051236_Initial.cs
> +﻿using Microsoft.EntityFrameworkCore.Migrations;
I suppose it is not

2023-08-27 22:46 UTC, xalluna commented on TcgPocket/Startup.cs
> +        // builder;
I copied code from a console App I used with EF core. I had to do this manually, but `WebHostBuilder" does this automagically.

2023-08-27 22:47 UTC, xalluna commented on TcgPocket/Migrations/20230826051236_Initial.cs
> +﻿using Microsoft.EntityFrameworkCore.Migrations;
I didn't realize that migration '0' was there by default

2023-08-27 22:59 UTC, gbrad777 approved these changes

2023-08-27 23:01 UTC, merged